# Configuration for the Subtext company.
# Do not put sensitive data in this file (use environment variables instead).

default: &default
  emails:
    advertising:    ads@subtext.org
    batch_jobs:     jobs@dailyuv.com
    listserv:       uppervalley-request@dailyuv.com
    moderation:     dailyuv@subtext.org
    no_reply:       noreply@dailyuv.com
    notifications:  notifications@dailyuv.com
    support:        dailyuv@subtext.org
    sunsetting_ads: aileen.lem@subtext.org

  email_outreach:
    welcome:
      subject: "Welcome to DailyUV!"
      template_id: 273041
    bookmarking:
      subject: "Bookmark your favorite DailyUV posts"
      template_id: 273057
    subscribe_to_digests:
      subject: "No more FOMO on the newsfeed"
      template_id: 273061
    finding_comments:
      subject: "Your comments are unforgettable"
      template_id: 273065
    initial_market_post:
      subject: "Nice going on your Market post. Don't stop there!"
      template_id: 273037
    initial_event_post:
      subject: "Nice going on your Event post. Don't stop there!"
      template_id: 273033
    blogger_welcome:
      subject: "Welcome to Your DailyUV Blog!"
      template_id: 273077
    blogger_reminder:
      subject: "Trouble getting your blog off the ground?"
      template_id: 273089
    first_blogger_post:
      subject: "Nice work on that first blog post!"
      template_id: 273081
    third_blogger_post:
      subject: "3 Blog Posts! Youâ€™re ready for this."
      template_id: 273093


production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
